### ISSUE TITLE
News tags do not fit in grid item box

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#103]
https://cambodia.pp.opendevelopmentmekong.net/news#!/story=post-92490

Note Special Economic Zone to the right also the first row of news boxes have overlap (1st and 3rd box)

![eco-zone](https://cloud.githubusercontent.com/assets/16559612/16899392/3ff11bbe-4bd0-11e6-8a20-4ad740471ba9.JPG)

**Comment by acorbi** [comment]
@jpeizer1 the issue you raised contains 2 issues. I have renamed this and splitted the other one in https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/105

For fixing this issue, and since the number of tags is not fixed, I have disabled the tags from the grid boxes (will appear once the user goes into the post)
