### ISSUE TITLE
Search enhancements for UI 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1032]
Some minor details re the layout/design of the horizontal presentation of the search page: 
@acorbi @DragonVirus @Huyeng 
![image](https://user-images.githubusercontent.com/14996905/27493393-bd309038-5817-11e7-8306-e2f67848381e.png)

- 1 & 3 - rounding edges of the search and filter boxes to be consistent. 
- 2 - the terminology and order of the resource types needs to be reassessed and agreed upon as there is less space horizontally I am suggesting the following: 
•	# ALL
•	# Agreements 
•	# Data
•	# Laws
•	# News (combine announcements here and give higher weight than news) 
•	# Profiles
•	# Publications
•	# Topics
Now that we have an ALL then we can list the others in Alphabetical order  - I have reduced the term to single word phrases and suggest that we actually add the # of records at the beginning rather than have a hover which isn't as apparent at a glance how many records there are. 
4 - Considering that we have restricted the taxonomy and tagging to <5 terms then we need to restrict the display of records with far too many tags - as an interim solution - till we can correct all of these records that have been inappropriately tagged. 

<img width="912" alt="odc-search2" src="https://user-images.githubusercontent.com/14996905/27493745-e6df6bd8-5818-11e7-8727-72b0f2207bcf.PNG">
1 - The actual metadata displayed should be consistent as much as possible but each resource type has different parameters that are important to display to the user. But that said the spacing needs to be improved so that there's distinctions between each field - currently this is not as neat as it could be. Suggestion: 
* Reduce paragraph spacing for taxonomy and keywords
* Increased paragraph gap between description and author/corporate 
* Can we hyperlink the news URL instead of listing it 
2 - The paragraph spacing between records needs to be consistent in size - this seems currently to be random.

<img width="722" alt="odc-search3" src="https://user-images.githubusercontent.com/14996905/27494069-41f1bc6e-581a-11e7-9482-aecb4c309930.PNG">
1 - For datasets please add the source 
2 - Again the spacing between each record is not consistent - this obviously is so that the two columns can be even for the start of each new record but this means there are huge spaces. Please make this defaulted by also standardising the length text displayed by any given field - with option to expand - so that we don't have this issue. 
3 - The majority of the thumb nails I've come across do not display? This will also affect the above issue - my personal opinion is that we do not display the thumbnail as we can't ensure that all records will have a displayed image . 

![image](https://user-images.githubusercontent.com/14996905/27494212-df955ff2-581a-11e7-8e1d-37c180395afa.png)
Library records need to now present author/corporate: 
![image](https://user-images.githubusercontent.com/14996905/27494252-0e2a2c12-581b-11e7-9057-b65562d26319.png)

![image](https://user-images.githubusercontent.com/14996905/27494284-309fafba-581b-11e7-9676-3ff7307281f2.png)
MAPS 
- I don't like the thumbnails - it doesn't actually give any detail regarding the dataset, no metadata and the image is difficult to view. Makes the presentation irrelevant and uninformative. 
- Suggest moving back to a list. 

<img width="732" alt="odc-search4" src="https://user-images.githubusercontent.com/14996905/27494373-a0af24fc-581b-11e7-9057-80dc889a1e3a.PNG">
TOPICS
- There's something funny going on with the shadow display here. 

![image](https://user-images.githubusercontent.com/14996905/27494455-f6b865ac-581b-11e7-80ee-9a301780fe9a.png)
ANNOUNCEMENTS 
- Move download to bottom and conform with other resource types. 
- Apply above styling suggestions.

**Comment by acorbi** [comment]
@prustar 

> 2 -  ...Now that we have an ALL then we can list the others in Alphabetical order - I have reduced the term to single word phrases and suggest that we actually add the # of records at the beginning rather than have a hover which isn't as apparent at a glance how many records there are.

Renaming the content types should be done across the site (menus, related content widgets, etc..) So I would suggest to approach this as a separate Issue @DBishton @gimmemochi 

> 4 - Considering that we have restricted the taxonomy and tagging to <5 terms then we need to restrict the display of records with far too many tags - as an interim solution - till we can correct all of these records that have been inappropriately tagged.

The current implementation show a maximum of 5 topics and max 5 tags so there is no need to restrict the display of the records. Downside of the current implementation is that there is information missing/not displayed (i.e the rest of the tags/topics)

> 1 - For datasets please add the source

Let's address this issue separately on https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1035

> 3 - The majority of the thumb nails I've come across do not display? This will also affect the above issue - my personal opinion is that we do not display the thumbnail as we can't ensure that all records will have a displayed image . 

This might be due to the PWD protection of the PP environment which avoids the thumbnails to be rendered. This should not happen on prod.

> Library records need to now present author/corporate:

They do.

> I don't like the thumbnails - it doesn't actually give any detail regarding the dataset, no metadata and the image is difficult to view. Makes the presentation irrelevant and uninformative. Suggest moving back to a list.

@prustar can you then please provide your feedback on this related issue? https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/141

> TOPICS - There's something funny going on with the shadow display here. 

https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/150

> ANNOUNCEMENTS - Move download to bottom and conform with other resource types.

@prustar that is the current layout for those contents being rendered using the **list layout**, see:  https://pp.opendevelopmentcambodia.net/announcements

It is true that on the detail view the links are provided after the content:

![screenshot from 2017-06-26 16-19-33](https://user-images.githubusercontent.com/384894/27543714-421a5980-5a8b-11e7-8871-24841d5bde29.png)
https://pp.opendevelopmentcambodia.net/announcements/ministry-of-environment-offically-lunched-the-lexicon-of-climate-change-in-khmer/

@Huyeng I support @prustar suggestion to move them below the content, do you agree?

**Comment by acorbi** [comment]
An update on the last bullet from my last comment. The layout has now been changed as part of https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1042.

**Comment by acorbi** [comment]
@prustar see this thread, you mentioned it today. As you can see, tehre are some issues which have been already addressed, and some others where extracted into individual issues to be addressed separatedly. Would you please go through it and create individual issues for those things that are still outstanding? Then please close this issue.

**Comment by rtritt** [comment]
@acorbi @prustar 
Alex - I'm trying to follow this thread and the separate one.  Pyrou is traveling to a conference and will be tied up all next week, and will be in Yangon the following week.  Can you create the individual issues related to all of the outstanding issues and send a consolidated email to relevant parties (and me)  with links to each outstanding issue from this thread (including those that you have already pulled out as separate issues).  It would be really helpful to have links to them *(at least for me as a novice on github) so that they don't get lost in the vast # of issues on github. I'd like to see the team come to final agreement on all of the outstanding search related issues and close them all by next week so we can move on.

**Comment by acorbi** [comment]
@rtritt Here a comprehensive list of the existing issues which are still outstanding:

Renaming content types across the platform to make them shorter
https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1069

Add source on metadata fields to be shown for CKAN records
https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/1035

**Comment by acorbi** [comment]
I'm closing this issue, please see the linked outstanding issue.

Please mind that issues should be raised **individually** otherwise difficult to track, discuss, implement.

**Comment by prustar** [comment]
@acorbi -- I recognise that it works for **you** to break these issues in to sub-tasks but there is currently no method within Github that we are currently utilizing to track these collectively so these smaller sub tasks do go by the way side a lot of the time - thus resulting in an incomplete deliverable of the whole specification for one feature. Please propose a solution for how we can manage this in GitHub that makes sense and I'll be happy to do this.

**Comment by acorbi** [comment]
> but there is currently no method within Github that we are currently utilizing to track these collectively

Not quite true, you can assign them labels and therefore grouping them. If you currently cannot label issues or create new labels, tell me and we will fix it.

Another alternative would be to list those issues on a dedicated google doc where you can even also provide some context and mention other team members as it happens on github. See current milestone 2.4.0 for reference: https://docs.google.com/document/d/1oJkSMYfSaPeFuhXv8l-JnRusougrX_xd1eB7LuW90z4/edit
