### ISSUE TITLE
Add source on metadata fields to be shown for CKAN records

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#1035]
Raised by @prustar 

Suggestion to add the source of the dataset on **list layout** representation of CKAN contents along with date, topics, tags, etc..

![screenshot from 2017-06-26 16-10-01](https://user-images.githubusercontent.com/384894/27543250-fe0815b2-5a89-11e7-878d-33fc6fad3c2d.png)

@prustar Only for datasets? or for all 4 CKAN record types?

Which icon would you suggest for representing source, please provide suggestion from http://fontawesome.io/icons/

**Comment by Huyeng** [comment]
I'm not quite sure what do you mean the "the source of the dataset "? Could you prove some explanation please?

**Comment by acorbi** [comment]
@Huyeng With source I refer to the **odm_source** (datasets), **odm_laws_source** (laws records) and **odm_agreement_source** (agreements) metadata fields which indicate:

>  Ordered citations for all information sources that went into producing 
the dataset.

Quoted from https://wiki.opendevelopmentmekong.net/public:metadata

BTW: @prustar I noted that library records do not have a source field. Can you please check whether we would need to include this or maybe we are already using another field instead of this for that?

**Comment by prustar** [comment]
@acorbi  The source field only applies to datasets specifically because they are generally sourced from external parties, i.e. WB, ADB, UN, etc. For datasets it's important for users because they want to quickly identify where the data came from. Laws and agreements also have source fields but I'm not sure if this is as necessary to display for these record types. The source field in these resources are essentially the same as author in the library records which we already display.

One of the limitations will be that generally the source field is populated inconsistently so you may have short strings, just names or acronyms or sometimes long strings which affects the presentation. 

Would not know what symbol is appropriate - can we just say **source:** This would dispel any ambiguity relating to a symbol that might not be universally recognized by all the countries.

**Comment by acorbi** [comment]
Moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/202 for implementation
