### ISSUE TITLE
Responsive: Map explorer and thematic maps

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#1057]
## Description of the issue

On the Map explorer and the Map of profiles are not enough responsive on the mobile. Suggest to improve them to be more responsive. 

![screenshot_6](https://user-images.githubusercontent.com/6613530/27850277-b20a653e-617d-11e7-9b50-695271babffe.jpg)

## Proposed solution

- [ ] Adapt layout so the selection of layers on mobile is accessible via a [layers] button ( to implement using leaflet's custom controls mechanisms http://odoe.net/blog/custom-leaflet-control/ . See inc/jeo-scripts/fullscreen.js)

![screenshot from 2017-07-17 15-14-54](https://user-images.githubusercontent.com/384894/28269627-07972242-6b03-11e7-87a5-19f84eff55d0.png)
 
- [ ] Once the user clicks on the [layers] button, a sliding menu appears (similar to the one described on https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/issues/160) giving the user following options: 
  - Change base layer
  - Toggle active layers 

![screenshot from 2017-07-17 15-17-49](https://user-images.githubusercontent.com/384894/28269919-f763472e-6b03-11e7-89a1-6fe703f9f0ee.png)

the user will then have 2 options to exit this screen:
- Click on the [x] icon to close without applying changes
- if the user changes something the [x] icon will change to a "tick" [v] icon for the user to know that something has changed.

- [ ] Allow 4 base layers per row (if >4 another row is added)

- [ ] Separate base map and map layers areas with a horizontal divider and label

- [ ] Make sure this change applies to embeddable thematic maps and individual layers.

- [ ] study the possibility of disabling scrolling on map for mobile devices and just let users zoom in/out. Check leaflet configruation. Also make sure the layers are centered everytime a layer is enabled/disabled. http://leafletjs.com/

- [ ] Move fullscreen and print controls to the left (below the zoom and as implemented currently) and layers button to the right.

- [ ] Test the print a map function on mobile. If it does not work, we should hide it. (adding the hideOnMobileAndTablet class)

_update:_ I tested this on my phone and does not layout good, I would hide it on mobile
![photo_2017-07-18_17-08-24](https://user-images.githubusercontent.com/384894/28324468-c1096dba-6bdb-11e7-89e1-4eaf808a5a8a.jpg)

**Comment by acorbi** [comment]
The main problem is that the layer selection and legend box take too much space. To fix this we would:

- collapse the box by default on mobile
- reduce the size of the buttons ( Data layers and layers) by using icon instead of text.
- Adapt the base layer selection box to be rendered as a dropdown box (same as layer selection)
- study the possibility of disabling scrolling on map for mobile devices and just let users zoom in/out. Check leaflet configruation.http://leafletjs.com/

![screenshot from 2017-07-06 12-10-12](https://user-images.githubusercontent.com/384894/27906696-ea462920-6244-11e7-965c-d83f3e038305.png)
