### ISSUE TITLE
Enhance layouts for related datasets widget

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#1084]
Hi @acorbi ,

Please enhance the 'related datasets' widgets to allow the formatting options presented in the 'ODM contents same category' widgets -- grid and column layouts.

![image](https://user-images.githubusercontent.com/1206387/28067720-a1b1a960-666c-11e7-9f23-966895585291.png)

**Comment by acorbi** [comment]
@DBishton Since the formatting options presented in the 'ODM contents same category' widgets are pretty extense, and after estimating the effort needed to complete this task entirely, I have decided to implement a solution "in-between" which offers editors the possibility to select the templates as pictured in your screenshot above but without being able to leverage ALL possibilities that the other widgets offer such as those pictured below:

![screenshot from 2017-07-12 16-23-28](https://user-images.githubusercontent.com/384894/28122448-858ab1fc-671e-11e7-94e0-95b683b3685f.png)
![screenshot from 2017-07-12 16-23-34](https://user-images.githubusercontent.com/384894/28122449-858d1050-671e-11e7-96ba-6306a43f086c.png)

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wpckan/issues/324
