### ISSUE TITLE
Related resources widget is not rendering

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#1113]
@acorbi Related resources widget is not appearing in top widget area on this draft story: https://opendevelopmentmekong.net/?post_type=story&p=5625502&preview=true

Please investigate urgently.

**Comment by acorbi** [comment]
@DBishton The reason for this relies on the configuration/curation:

- In case of the **"Key publications"** you had specified **library** as Dataset type, it should read **library_record**. I have changed it and now the records appear:

![screenshot from 2017-07-18 16-05-18](https://user-images.githubusercontent.com/384894/28321218-fbf09498-6bd2-11e7-80cb-941df69f385b.png)

I just need to fix the issue which is not displaying the layout selection dropdown (investigating now)

- In case of the **"Key datasets"** they are not appearing because you have apparently not added them. The current list of curated related datasets is composed only by 4 library records...

![screenshot from 2017-07-18 16-03-25](https://user-images.githubusercontent.com/384894/28321249-0d07de4e-6bd3-11e7-9fb6-99cb0dd6743d.png)

if you share with me the titles (or better URLs) of the other 4 datasets to curate I can do it.

**Comment by acorbi** [comment]
@DBishton I fixed the issue which prevented us to selected the dataset-grid layout and configured the widgets accordingly.

![screenshot from 2017-07-18 16-25-34](https://user-images.githubusercontent.com/384894/28322227-d7ababec-6bd5-11e7-936e-39f826bd5d9c.png)

Now the only thing you need to do is add those manually-curated datasets so they show up

**Comment by acorbi** [comment]
closing this since there is nothing else to do on the tech side, please reopen if you consider.
