### ISSUE TITLE
Custom post widget not rendering

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#1114]
Custom posts widget is not rendering on this draft story; https://opendevelopmentmekong.net/?post_type=story&p=5625502&preview=true

Please investigate urgently.

**Comment by acorbi** [comment]
@DBishton Not sure if this is related but worth raising. On the **Story bottom** widget area (the one at the bottom of the page), the related news summaries widget shows WAY too many related posts:

![screenshot from 2017-07-18 15-27-24](https://user-images.githubusercontent.com/384894/28319302-c9ca0350-6bcd-11e7-9b55-9a9935367e22.png)

That makes the page load very slow, you should configure a limit on the widget to reduce the amount of boxes presented.

**Comment by acorbi** [comment]
According to the widget configuration on https://opendevelopmentmekong.net/wp-admin/post.php?post=5625502&action=edit they are properly showing up.

I have checked the **show thumbnail** checkbox to improve the config of that widget, allthough since the related news do not have any featured image, no thumbnail is shown.

![screenshot from 2017-07-18 16-09-10](https://user-images.githubusercontent.com/384894/28321496-afa1a522-6bd3-11e7-9617-6b2d7473713d.png)

Im closing this issue. please re-open if something is still outstanding
