### ISSUE TITLE
Link to our CKAN repository on WP

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#1190]
@acorbi or @Huyeng - I was speaking to a friend who use to work for OKFN and she noted that we don't provide a link to our CKAN instance github repository. Apparently this in violation of their copyright conditions and we should offer this at the base of the WP site so people can go to it. 

She also offered some advise regarding the use of CKAN behind the WP instance and I would like to discuss this with you when you are back.

**Comment by acorbi** [comment]
According to Adrià Mercader ( Lead developer at CKAN), this is not required. closing

**Comment by prustar** [comment]
@acorbi -- we should offer it nonetheless. I've had people inquire and would like to have it visible on the page somewhere so that we don't continuously get asked about this.

**Comment by acorbi** [comment]
@prustar what do people exactly ask for? 

- An evidence that ODM uses CKAN on the back-end? 

How about implementing what I initially proposed: https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/1198

- A link to our github repositories? both?

**Comment by prustar** [comment]
@acorbi - Data partners that I've been working with ask about the CKAN repository and metadata. The wiki isn't great for this - been meaning to update it. Would be easy for people to use our data if they could simply connect to the CKAN repository and then use it from there. 

People don't get that our site uses CKAN and that we have a database behind WP - conceptually this is very difficult for people. If we made a link to a page about our database and how it works this might be easier to get data contributors on as well. 

Plus regardless if Mercader says it's not necessary its still an open data site so we should be clear about what tools we are using.

**Comment by acorbi** [comment]
>  ask about the CKAN repository and metadata

@prustar What do you mean by CKAN repository here? The CKAN code? If you refer to metadata, there are the JSON schemas for each of the datatypes we manage (i.e https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/blob/master/ckanext/odm_dataset/odm_dataset_schema.json) which would be potentially interesting for them, **but only** if they are developers. Otherwise[ the metadata wiki guide](https://wiki.opendevelopmentmekong.net/public:metadata#ckan_s_default_metadata_fields) is the best reference you can point non-technical people to, at this point. 

> People don't get that our site uses CKAN and that we have a database behind WP - conceptually this is very difficult for people. If we made a link to a page about our database and how it works this might be easier to get data contributors on as well.

That would be https://wiki.opendevelopmentmekong.net/public:system_s_architecture, needs to be adapted to reflect that CKAN is now hidden behind WP, but that would be the document I would point data contributors to.

> Plus regardless if Mercader says it's not necessary its still an open data site so we should be clear about what tools we are using.

Agree. Just note your initial description of this issue / change request:

> Apparently this in violation of their copyright conditions and we should offer this at the base of the WP site so people can go to it.

**Comment by acorbi** [comment]
@gimmemochi @prustar I have adapted the text on the footer and added a link to the [System's architecture page on the wiki](https://wiki.opendevelopmentmekong.net/public:system_s_architecture). It looks like pictured below:

![screenshot from 2017-10-25 10-09-22](https://user-images.githubusercontent.com/384894/31987616-a2f3fb04-b96c-11e7-91cc-1efa03337f29.png)

Is this OK to go live? any other changes you would suggest?

**Comment by prustar** [comment]
@acorbi Yes that's great!

**Comment by acorbi** [comment]
sure. will do later today
