### ISSUE TITLE
Date inconsistencies: news summaries on Homepage vs. News archive page

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1203]
@acorbi Currently, on the homepage, the date of the news summaries is "publication date by the original news source". However, on the news archive page, the date of the news summaries is "date when the news summary is published/modified on ODM". See below for examples:

On October 2nd, I added two summaries of news article -- one was published on September 29 and the other September 28. The date should be September 29 for the first, and September 20 for both on both the Homepage and News archive page.

Please change the date in the news archive page to reflect published date. 

**HOMEPAGE**
<img width="1280" alt="screen shot 2017-10-02 at 2 14 47 pm" src="https://user-images.githubusercontent.com/6489398/31067593-d799542c-a77d-11e7-97c6-65aef654c4c4.png">
**NEWS ARCHIVE PAGE** 
<img width="1277" alt="screen shot 2017-10-02 at 2 14 21 pm" src="https://user-images.githubusercontent.com/6489398/31067594-d9297d62-a77d-11e7-8cb9-0a86a0aeaeda.png">

Let me know if you have questions.

**Comment by acorbi** [comment]
@gimmemochi As indicated on https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#showing_creation_date_or_modification_date_on_single_posts_and_archive_pages and the screenshot below, the date shown on the **single** and **archive** pages of the posts on WP (news-articles, announcements, topics, etc...) can be configured under **Appearance > Open Development

![screenshot from 2017-10-02 11-49-14](https://user-images.githubusercontent.com/384894/31072336-bbb243ce-a767-11e7-8473-4d420d36558e.png)

The date shown on the widgets on the homepage is configured as indicated on https://wiki.opendevelopmentmekong.net/partners:configuring_frontend_2_0#odm_custom_posts_widget_in_detail

In order to keep consistency, both need to be configured with the same date. In order to fix this issue, I have changed the configuration of the **single** and **archive** pages to show the creation date (it was modification date before).

Closing this issue
