### ISSUE TITLE
MAP Catalog -- Confusing

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#121]
Am not sure what I should be seeing in the map catalog but its confusing

If I click some like https://cambodia.pp.opendevelopmentmekong.net/layers/radio-wmc/
I get the taxonomy index in English
![mapcatalog-eng](https://cloud.githubusercontent.com/assets/16559612/16904012/d34a5b42-4c5b-11e6-91c3-9897aad7f1b5.JPG)

If I click others like https://cambodia.pp.opendevelopmentmekong.net/km/layers/hydropower-reservoirs/
I get part Khmer and part English
![map-catalog-khmer](https://cloud.githubusercontent.com/assets/16559612/16904015/dc9b6704-4c5b-11e6-856b-0a34804c7782.JPG)

But why am I getting the index? Shouldn't I be accessing a CKAN record with the map file for either RADIO WMC or Hydropower if I click on those?

This is related to when you click the KHMER Flag #123

**Comment by gimmemochi** [comment]
On the same topic of Map catalogue, @prustar @acorbi are there benefits for letting users search the map or browse the map catalogue? Currently, if user use the search bar (see pink box), search result would show a new page, where "maps" are not listed as a content type. 

https://cambodia.pp.opendevelopmentmekong.net/layers
<img width="1265" alt="screen shot 2016-07-18 at 4 40 28 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911155/087e095c-4d07-11e6-813c-270f786a394b.png">

https://cambodia.pp.opendevelopmentmekong.net/?s=wildlife+sanctuary
<img width="1266" alt="screen shot 2016-07-18 at 4 43 19 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911159/0c31fefa-4d07-11e6-93bc-4199ed644038.png">

**Comment by gimmemochi** [comment]
@acorbi I saw this when clicking on "Forest Cover" thematic map: https://cambodia.pp.opendevelopmentmekong.net/km/maps/forest-cover/

<img width="1215" alt="screen shot 2016-07-18 at 4 55 31 pm" src="https://cloud.githubusercontent.com/assets/6489398/16911536/3d5ff458-4d09-11e6-9560-896aaeae5852.png">

Also saw the same error message when clicking on economic land concession on the Map Catalog page (not the list of categories as presented when clicked on WMC radio or Hydropower maps in the map catalog).
https://cambodia.pp.opendevelopmentmekong.net/km/layers/economic-land-concessions-including-adjustments-to-concessions/

**Comment by prustar** [comment]
@gimmemochi - the map catalogue is a new function and hasn't yet been fully developed. 
@acorbi - The distinction between spatial and non-spatial data is an issue again here. Without consistent and logical method to distinguish it becomes increasing difficult to filter.

**Comment by acorbi** [comment]
OK, this Issue is getting a bit too mixed up.

@jpeizer1 map catalogue is in the making. In the future, the elements listed on https://cambodia.pp.opendevelopmentmekong.net/layers (the map layers) will just expose a thumbnail and a download button which would take the user to the corresponding **dataset detail page** e.g https://cambodia.pp.opendevelopmentmekong.net/dataset/?id=draft-law-on-environment-impact-assessment-3rd-revision

@gimmemochi your request of also exposing maps on the search results is good. @prustar don't you think. I have created following issue to address it: https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/159

@prustar let's have a conversation on the advanced search page and continue discussion on issue #145
