### ISSUE TITLE
ODV Taxonomy (EN) is not consistent with the OD Taxonomy

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#1210]
@acorbi It appears that the "Categories" (ODV Taxonomy on WP) are not of the latest version and thus is not consistent with the ODI taxonomy. The current ODI Taxonomy does not include ":" sign. For example "Art: policy and administration". 
Is there an way to import latest taxonomy (EN) to ODV?

https://vietnam.opendevelopmentmekong.net/wp-admin/edit-tags.php?taxonomy=category&post_type=news-article&s=%3A
![screen shot 2017-10-18 at 4 20 55 pm](https://user-images.githubusercontent.com/6489398/31710833-66577e60-b420-11e7-8233-f24b0286ec5e.png)

cc: @prustar @mailannguyen

**Comment by acorbi** [comment]
@gimmemochi yes, the categories can be imported/exported. Let me put together a quick GUIDE on the WIKI and share it with you over here.

**Comment by prustar** [comment]
@gimmemochi @acorbi -- if you are updating the taxonomy for Vietnam could you please simultaneously update for Laos and Thailand so that when we get to translating these they are working off the correct terms.

**Comment by gimmemochi** [comment]
@acorbi Any progress updates on this?

**Comment by acorbi** [comment]
@gimmemochi @prustar I have been dedicating a bit of time to this issue this week but was hoping to be able to focus today, since I am working full day.

I have drafted following doc https://docs.google.com/document/d/1yuvp7UTtmIao_anF1EwppBjXtwYNoMqJKwBZtILUYzc/edit which states/proposes 3 main points:

- The categories across countries sites differ considerably in structure
- So far, I have not been able to come up with a solid and automatic mechanism for harmonizing them to the universal taxonomy definition, besides manual editing. This is where I want to spend more time and see if I can save us that considerable effort.
- Once harmonized, the category management on WP sites needs to be restricted for admins, so these categories are not changed that easily.

please add your thoughts/comments on the doc

**Comment by acorbi** [comment]
@gimmemochi @prustar Categories on ODV, ODL and ODT are now aligned to the universal taxonomy v1.1.

Also, management access to the categories on WP dashboard is now restricted only to admins to avoid this situation happening again as drafted on https://docs.google.com/document/d/1yuvp7UTtmIao_anF1EwppBjXtwYNoMqJKwBZtILUYzc/edit#
