### ISSUE TITLE
ODC download page is confusing

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_theme#1256]
I have received comments from a group of user, who never use ODC website before that  Download Map page is so confusing and they difficulty download the dataset for 2 reasons.

1.  It is about the download bar. Please see below: 
![image](https://user-images.githubusercontent.com/18112596/36657124-f84db1f6-1afd-11e8-8f40-c2e1cc797326.png)
The user doesn't understand what those buttons are used for. And they miss thinking that the download button is for download dataset.

2. It is about the map. With the current function, if the users click on the jpeg map, it will pop up and show the map. If the users click on the title of the map, it will take the users to the dataset. Unfortunately, the user doesn't under this function and they are not able to download the dataset from ODC website.

![image](https://user-images.githubusercontent.com/18112596/36657258-733053e2-1afe-11e8-9444-4c01cd39e6c2.png)

**Comment by acorbi** [comment]
Hi @punwath , thanks for your input. Do you have any ideas on how to improve this? Have you discussed internally at ODC and come up with a suggestion for improvement? If so, please share it here or in any type of shared doc

**Comment by Huyeng** [comment]
Yes, it made users confuse and the users frequently asked about this. The three buttons RSS Feed, Get GeoJSON and Download don't work except the RSS Feed button. Thus, we can remove three buttons or remove GeoJSON and Download buttons and keep only RSS Feed. 

For the pop-up image, we have already discussed by adding the button link on popup image and I will fix it.

**Comment by Huyeng** [comment]
Result: ![screenshot_4](https://user-images.githubusercontent.com/6613530/37162418-ca3e95e6-2327-11e8-997e-748c387f0c61.jpg)

**Comment by prustar** [comment]
@punwath @Huyeng -- Those tabs are part of the open data standards that we have initiated. They don't actually work which surprised me, only the RSS feeds seem to work. @acorbi correct me if I'm wrong but if a developer wanted to harvest data from our site they would use the Geojson string to import the data into their code? 

Users also need to be separated and distinguished. If a user doesn't understand the function it doesn't necessarily mean that another user won't find this function useful. However I'm not sure if we've monitored any analytics on if people have selected these options or not on the platform? @acorbi could you please tell us if google analytics is tracked here? Unfortunately I see that the buttons don't work. 

Users also need to be educated as well so I think that we should know what all of the features we offer on the platform are and be able to explain it to the user. In this way they have the choice to use it or not. 

Please also consider that the entire interface for the map function is going to be revamped shortly as we are currently not managing the data in an effective cataloging system. I have previously shared this with you both.

**Comment by acorbi** [comment]
@punwath  @Huyeng @prustar The **Get GEOJson** and **Download** buttons are part of the geo-spatial functionalities provided by the JEO theme. They "should" work as follows:

Wordpress content will be geo-tagged via the **address and geolocation** box withing the editing screen:

![screenshot from 2018-03-12 11-04-46](https://user-images.githubusercontent.com/384894/37277863-41cbf412-25e6-11e8-98db-e1e7292bb199.png)

Once a geo-location is assigned to the wordpress content ( post, page, profile page, etc...) and the user clicks on one of those 2 buttons mentioned above, the entry should be available on the geojson file to be downloaded.

The functionality seems to be indeed currently broken since I tried adding a geo-location to one of those profile pages and clicked the button, but obtained an empty collection:

```
> @acorbi could you please tell us if google analytics is tracked here?

Nope, these buttons are not tracked. Adding the tracking of the corresponding click-events would be an easy task though.

@prustar please indicate how you want to move on with this, if this part of the system is going to be revamped, then it might not be worth to invest time on fixing the current functionality.

{
  "type": "FeatureCollection",
  "features": []
}
```

**Comment by prustar** [comment]
@acorbi thanks for explaining the function.  I don't think it's worth investing in it as it will all be charged shortly.

**Comment by Huyeng** [comment]
Like Alex said, the Geojson button works together with geo-tagged of Wordpress post which contains the address and geolocation. As this is the main page of download map, so showing the Geojosn and Download button on that page is not make sense. However, instead of the Geojson button, maybe we can add a button that can link for our Geoserver. What do you think?

**Comment by prustar** [comment]
@Huyeng - This is going to be changed when we implement the upgrade for geospatial data. It will mean that CKAN will be used more efficiently and effectively to manage geospatial data and synchronized with Geoserver directly. It's really difficult for people to navigate geoserver unless you are familiar with it so I wouldn't do that just yet.

**Comment by punwath** [comment]
@prustar Does "the upgrade for geospatial data" refer to the implementation of Map Terra JS on the interactive map?
