### ISSUE TITLE
Land Page Opener with links difficult to see

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#257]
Both Link and Text fonts on Image:

https://pp.opendevelopmentmekong.net/topics/land/

![capture](https://cloud.githubusercontent.com/assets/16559612/17613840/5d404c9e-602f-11e6-897b-b5cf83be904d.JPG)

**Comment by Huyeng** [comment]
@DBishton, please help to check that.

**Comment by DBishton** [comment]
Hi @jpeizer1 and @Huyeng,

This issue is already covered in https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/993

The new theme is not detecting the styling changes made to this plugin (reflects older styling). Styling should appear as it does on production: https://opendevelopmentmekong.net/topics/land

![image](https://cloud.githubusercontent.com/assets/1206387/17654657/9df68f3a-62cf-11e6-8e85-f93be230950c.png)
