### ISSUE TITLE
Add option to ODM Custom posts widget to sort by creation/modification date

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_theme#341]
On the Home page of OD Cambodia site, you will see under Public announcement: "Result of EdC’s electricity connection in Phnom Penh" and "Joint statement on the draft Law on Associations and Non-Governmental Organizations (LANGO)", those announcements were published since 2015, not the recently or the latest one. When I go to Edit announcement, I found the published date on Publish navigation showing that it was published in 2015, but when I preview it on the front end of live site, it show today date (the latest Modified Date) not its publication date.

**Comment by acorbi** [comment]
Hi @vatana92 the contents are sorted by modification date. This is the expected behaviour.

We have following possibilities to find a solution that work for everyone:
- we implement an option on the widget to allow the editors to specify whether the news should be sorted by modification date or publication date.
- If you want, you can request me to change the modification date of specific posts. I can do it by modifying directly the Database.

Looping @DBishton in this conversation since this relates to editorial

**Comment by Huyeng** [comment]
@dan and @acorbi, it is very confuse to show the modification next to the title of the posts that always expected as the published date. 
News and Announcements should show and short by published date.

**Comment by acorbi** [comment]
@Huyeng @DBishton I believe the best option then is to add that option on the **ODM Custom posts** widget to allow editors to filter by modification or creation date. Do you agree?

Im changing the title of this issue to reflect this.

**Comment by Huyeng** [comment]
Providing the option this a great idea, but the default option of sorting should be created date. 
However,  we should identify clearly between the modification date and creation date of post to voice confusing.
