### ISSUE TITLE
Draft layers showing on map explorer

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#370]
https://myanmar.opendevelopmentmekong.net/map-explorer/

**Comment by acorbi** [comment]
@prustar Could you please cleanup those test layers. it would be good to make sure that the other country sites do not ave any as well....

**Comment by prustar** [comment]
@acorbi - the test page shouldn't be visible to the public I will check the category settings. 

Did @Huyeng fix the map preview function in Wordpress? If so then the partners won't need to use this test page anymore to view layers prior to publishing? Otherwise this is the only way they can view the layers before they make them public.

**Comment by acorbi** [comment]
@prustar true. I recall we had an Issue which addressed the fact that draft layers where showing up on the map explorer. I cannot find it though but I would like to make sure that this issue is fixed . I am going to change the title of this Issue accordingly:

**Comment by jpeizer1** [comment]
This is not fixed...  https://myanmar.opendevelopmentmekong.net/map-explorer/

Is there a process where people actually go the site and check that fixes are done before closing issues? If not there must be one.  

![capture](https://cloud.githubusercontent.com/assets/16559612/18253389/5fd2c022-7362-11e6-9edf-d353851cdd4c.jpg)
