### ISSUE TITLE
Map explorer: Links and downloads still point to CKAN

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#391]
All the downloads and metadata links need to be redirected.

**Comment by acorbi** [comment]
@Huyeng we should look at fixing this issue asap in order to keep consistency on the user experience
For this, we should use the **wpckan_get_link_to_dataset** function exposed by WPCKAN on https://github.com/OpenDevelopmentMekong/wpckan/blob/master/utils/wpckan-utils.php#L194 which returns the wished link by just passing the dataset name.

**Comment by acorbi** [comment]
@huyeng I have been thinking about how to implement this the best and my suggestion is the following:

On the **Edit layer** screen, we change the **Download URL field** so instead, the editors will input the ID of the dataset. This change would also make possible to maintain just 1 URL for ALL languages instead of 1 URL for each language (which can become a problem in the future). With this, the code could just use the  **wpckan_get_link_to_dataset ** function to link the layer to the corresponding dataset detail page.

The problem with this approach is that we would need to adapt all the currently existing layers, for that, we should be able to define SQL queries to modify the data on the DB directly.

What do you think?

**Comment by Huyeng** [comment]
@checking with mappers who entry the map layers, they prefer copy and add the full address url rather than the ID. They said that copy the only ID of dataset, can make some mistakes because some url contains other the query strings, and they don't familiar with those url strings. That's good point to consider. To avoid the error due to the human being mistake in taking the ID of dataset, I think we should keep this way.

To change the Urls that point to CKan  to WP instead we can do it with the php script will be easier than updating the url in DB with SQL query.
