### ISSUE TITLE
Curatable widgets for stories via magic fields 

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#394]
Please implement discussed enhanced functionality for story widget areas: allowing editors to select individual content elements to appear on individual stories.

**Comment by acorbi** [comment]
@DBishton this is now possible thanks to the wp-widget-pages plugin that I integrated some weeks ago. Now all content types such as stories expose a metabox at the bottom of the editing screen which let's you specify widgets for individual posts in order to override the default widget configuration:

![screenshot from 2016-11-22 23-46-34](https://cloud.githubusercontent.com/assets/384894/20545161/ee2ee056-b10d-11e6-91c5-800598eba3fe.png)

Im closing this issue since it is now fixed
