### ISSUE TITLE
Post-type "Page" doesn't show bullet points

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#420]
@acorbi I noticed the Pages do not show bullet points. Below is an example from our Terms of use page: https://opendevelopmentmekong.net/terms-of-use/ I've attached a screenshot of the text with bullet points from the editor dashboard on WP for comparison. 

![screen shot 2016-09-16 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/6489398/18578584/0e09b680-7c1b-11e6-93ca-225f76e364af.png)
![screen shot 2016-09-16 at 2 33 21 pm](https://cloud.githubusercontent.com/assets/6489398/18578588/0fbe02d8-7c1b-11e6-9719-c8a66562d685.png)

**Comment by acorbi** [comment]
@gimmemochi @DBishton this is now fixed, please make sure that the indention of those listed element is consistant though. It needs to be adjusted on the wordpress editor because currently looks like below:

![screenshot from 2016-09-20 19-00-41](https://cloud.githubusercontent.com/assets/384894/18680560/8b9a3100-7f64-11e6-90a9-a8977bbd92b7.png)
