### ISSUE TITLE
Define and implement layout for data page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#50]
@prustar we need to define which contents we want to show the user when they click on the DATA menu button on the upcoming frontend version. Currently, we have basically a blank canvas where we need to define which kind of information gets listed. This will be done using Wordpress widgets which allow defining dynamically which contents go where on the layout.

To give you an idea on which kind of widgets we can count with:

- List datasets by dataset type
- List datasets by dataset type filtered by search query (e.g forest)
- List datasets by dataset type filtered by any metadata field or combination of them ( e.g dates, taxonomy, etc..)
- List datasets from a sparql filtered by CKAN organization
- List datasets from a sparql endpoint using wpsparql

All this widgets can be added multiple times and positioned across a column/row based layout.

I have added a basic sketch on https://docs.google.com/drawings/d/1TwnOK1lvrbEidrO48MfclkotAP_8HHXeKIksIHcJdSY/edit, with an initial sketch on a possible layout, can you please iterate my proposal?? I need your input on this in order to implement the page template.

**Comment by prustar** [comment]
@acorbi -- provided some comments on your sketch. 

One thing to keep in mind when doing this design is that the database and each of the three record types are changing and will require separate treatment. Already the Law & Policies will be displayed in separate law compendiums for each country and regionally (hopefully) and as we've seen there's a need to manage geospatial metadata separately (to be developed), this leaves library and normal datasets to manage here. 

The search function for the database should allow for filters specific to the available parameters in the database i.e. not just taxonomy but dataset type, organisation, language, country/region, date filter, licensing/copyright etc. This does not take into consideration the complexity of separating geospatial data and their attributes yet. This is another matter that needs to be addressed separately.  Also to consider is when laws & policies are selected does this take them to the law compendium separately or do we integrate here? I believe we should bring up the results but manage these separately as we have already designed this relationally so it can standalone in the law compendium. 

See example of top search box(es): 
![image](https://cloud.githubusercontent.com/assets/14996905/16610073/00663cba-4359-11e6-8857-46f37864c2ec.png)
After selecting advanced: 
![image](https://cloud.githubusercontent.com/assets/14996905/16610086/16251d78-4359-11e6-8ebd-4351d748b3b0.png)

Rather than a traditional statistics box why not integrate the states into the selection options. I have provided a visual for this on the design. The user can select a box and is taken to the results. Options to filter this visual by taxonomy, dataset type and time. 

Once you've laid out this first page then the **second design** needs to be developed on bringing up the results and how to manage this. On this page the user has selected the parameters that they requested. The results should bring up the most relevant records to that selection -- This might need some further thoughts and trial and error testing to get it right. 

This second page should then have filter functionality as well, for i.e. record type, taxonomy, date (of record - not uploaded into CKAN). These options should display regardless of existing filters selected in the preliminary search to allow for users to adjust them if they don't find what they are looking for. 

The **third page** after selecting the record of choice is presenting that record to the user.... this is another design. I have already provided feedback on metadata fields to present for datasets, I can additionally do this for the library records, Laws & Policies should have there own within the law compendium as well. We should provide a short and detailed view options to the user. 

Lets set aside sometime to discuss further if need be.

**Comment by prustar** [comment]
See mimu.myanmar as alternative example for not having advanced search at top but map of region/country. 

![image](https://cloud.githubusercontent.com/assets/14996905/16610663/f3d088ee-435c-11e6-898a-7d09b1d42c82.png)

**Comment by acorbi** [comment]
@prustar Im assigning @DragonVirus to this Issue so she is informed.

@DragonVirus In the following days we are going to have conversations about dashboards and data visualizations which could be re-used in this data page we are currently drafting. We should be creating Wordpress Widgets so they can be placed and re-used on different parts of the frontend

**Comment by prustar** [comment]
1st - Data page

List of datasets should have not display the description. 
![dataset3](https://cloud.githubusercontent.com/assets/14996905/16911901/7a0e1650-4ce1-11e6-9713-8ed510d32274.JPG)

Perhaps we can use the big white space on the right to display the description and an image of the resource - extracted from CKAN.

**Comment by acorbi** [comment]
Sketches for proposed layout on:
- https://docs.google.com/drawings/d/1TwnOK1lvrbEidrO48MfclkotAP_8HHXeKIksIHcJdSY/edit
- https://docs.google.com/drawings/d/1ThGpbwZwq7RrqjnUjz_8i8TUN1lCfOFUKyogQcUZvUo/edit

**Comment by acorbi** [comment]
@acorbi - initial comments are:

- in the search under country 'mekong' this is duplicated by the 'all' option which I'm assuming will bring up the same records? Or are you refering to those records uploaded by ODM specifically ? This could be confusing to the user - not sure how to circumvent.

- the listing of the datasets in the three categories currently are ranked according to the number of people opening them yet it's clear that it is actually us going into edit these records and there is not a true prepresentation of the popularity of any of these records to the user. - Can you please refactor so that it is responding to users and exclude all of us from the result.

**Comment by prustar** [comment]
@acorbi - just a thought on the first point above - perhaps remove MEKONG and replace with REGIONAL this indicates that its datasets specifically mentioning the countries as a group focus and then ALL would be any article relating to the search parameters regardless of country specifications.

**Comment by acorbi** [comment]
@prustar I have implemented and deployed following changes/improvements:

1. Changed "Popular datasets" to "Most viewed datasets"
2. Presenting the statistics in one line
![screenshot from 2016-08-22 12-17-35](https://cloud.githubusercontent.com/assets/384894/17851518/a983ac6e-6862-11e6-84c2-336dd2b0c9d3.png)
3. Added logic to display "more on the law compendium" link when Laws are selected on the dataset type filter.
![screenshot from 2016-08-22 12-17-15](https://cloud.githubusercontent.com/assets/384894/17851532/b8fd1892-6862-11e6-8589-ded6ea987ca3.png)

Since this Issues has become quite big I am closing it. new feature/change request should be done in separate Issues.
