### ISSUE TITLE
Create disclaimer popup to be displayed on ODT and ODL

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#598]
Hi @acorbi ,

Please create a disclaimer popup for OD Laos and OD Thailand that contains the following text:

"Open Development Initiative supports a network of organizations co-managing a common open data and knowledge platform to illuminate development trends in the Lower Mekong region at country and regional levels. Would you like to join efforts with us in building a data and information ecosystem to support transparent sharing of development data and inform constructive dialogue and decision making for sustainable development in Laos? We are looking for national partners to contribute to establishing Open Development Laos. Learn about how you may participate here. "

The disclaimer should also appear on the Land topic page with a slightly different text:

"Open Development Initiative is currently seeking partners to manage Open Development Laos. This page is published here to demonstrate a redesigned user interface with improved navigation and content discoverability. The country site selector on the top bar allows users to discover similar content on another country site or the regional site. Click on the  Open Development Mekong logo on the country selector bar to read about land governance at the regional level or click on the  Open Development Cambodia logo to read about land governance in Cambodia. Would you like to contribute to Open Development Laos? Please get in touch with us. "

**Comment by acorbi** [comment]
@DBishton @gimmemochi @jpeizer1 This is what I have implemented:

on Laos and Thailand PP sites (http://laos.pp.opendevelopmentmekong.net/ and http://thailand.pp.opendevelopmentmekong.net/) you will see that the disclaimer is now floating on the bottom of the site. It can be dismissed by clicking the button and, since a cookie is stored in the browser when the user dismisses it, it does not appear once dismissed.

The disclaimer appears on all pages (also map explorer).

![screenshot from 2016-11-08 15-09-51](https://cloud.githubusercontent.com/assets/384894/20102962/54e8b480-a5c8-11e6-9182-3b954219ce1a.png)
 
![screenshot from 2016-11-08 15-12-49](https://cloud.githubusercontent.com/assets/384894/20102971/59abfffe-a5c8-11e6-9b86-583b42f8c2e5.png)

![screenshot from 2016-11-08 15-30-03](https://cloud.githubusercontent.com/assets/384894/20102973/5abb36b2-a5c8-11e6-9d32-486c986a3528.png)

Regarding the disclaimer on the Land pages, currently there is only the possibility of defining 1 disclaimer per country site, to be presented across all the different pages of it. The solution for having a specific disclaimer on the Land pages would be to add it as part of the Topic's content. Something like the mockup below:

![screenshot from 2016-11-08 15-12-29](https://cloud.githubusercontent.com/assets/384894/20103067/c48a8174-a5c8-11e6-9061-c487a9936b93.png)

@DBishton you should be able to do this on your own.

So, questions:

- Do you like the proposed solution currently deployed on PP?
- On the first text, where does the word **here** ( as in *Learn about how you may participate here.*) need to link to? @gimmemochi ?

**Comment by acorbi** [comment]
@Huyeng @ChandaraKhun if https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/600 is merged, this style will be applied to all sites including ODC. What are your thoughts about the layout/style change?

**Comment by acorbi** [comment]
@DBishton @jpeizer1 @gimmemochi @prustar currently, due to other deployments on PP, the code with the new disclaimers is not available for testing. Please review the screenshots above. If needed I can demo you the implementation.

**Comment by DBishton** [comment]
@acorbi Many thanks for the work on this. This implementation looks good to me -- thanks for the detailed description in the absence of being able to test them on PP.

@jpeizer1 @prustar @gimmemochi @ChandaraKhun @Huyeng the purpose of this mock-up was to gather opinions on this pop-up disclaimer as described and pictured above, versus a more static approach as is currently in place on ODC -- a permanent header that can't be dismissed on every page except map explorer.

![image](https://cloud.githubusercontent.com/assets/1206387/20175508/a77e9fbc-a775-11e6-9aba-9427893064b3.png)


The intention with this proposed pop-up solution is to display it on all pages, but have it be dismissable, so it is consistent in appearance, but can be dismissed for those needing full screen real estate (especially for the map explorer).

Please let us know which option you prefer.

**Comment by acorbi** [comment]
@ChandaraKhun @Huyeng can you please provide some input on the proposed change? thanks

**Comment by Huyeng** [comment]
@acorbi, we will back to you soon after discussion.

**Comment by acorbi** [comment]
@Huyeng great! looking forward to your feedback. you can deploy the branch impl-598 to test the implementation in poroduction

**Comment by Huyeng** [comment]
@acorbi, after discussing with the team, we prefer to show the notification/disclaimer as what we currently have. However, we like the idea and the function to provide the option to hide/close the notification next to the container. 
Using the pop-up disclaimer at the footer, it makes the window to narrow. It seems like to focus/require the users to close the disclaimer if they would like to view larger.  Some of them though that it likes advertising.

**Comment by DBishton** [comment]
@Huyeng Thank you for gathering feedback of the ODC team. Is your suggestion to retain the functionality of the new disclaimer (pop up, dismissable), but change the position on the screen?

**Comment by Huyeng** [comment]
Add the close function like the either option on the screenshot:

![screenshot_1](https://cloud.githubusercontent.com/assets/6613530/20956037/1d34178c-bc7a-11e6-85b8-799fbb8966ad.jpg)

**Comment by acorbi** [comment]
@DBishton @Huyeng 

- We will keep the notification where it is BUT add the dismissing functionality
- We will show the disclaimer ALSO on  the map explorer
- Alex will do a couple of mockups with white and/or coloured backgrounds which should be reviewed quickly

**Comment by jpeizer1** [comment]
@acorbi @dbishton -- Does this issue really require yet another round of consensus opinion on a simple background (and over a  month already to execute)? The current disclaimer has a white background. All we are doing is making it a popup. Rather than spending another 1-2 weeks to gain consensus  and then possibly leaving it for even more weeks while people go off on holiday -- wouldn't it be more logical to put the thing up with the same white background it has now and then change the color if people have issues with it? Honestly, do we really want to draw people's attention to clicking a link to the old ODC site by COLORING the background of the disclaimer message and drawing people's attention to it? We already have 2400 users a month accessing the old archive site in November, up from 1700 in October and 500 in September. These stats are going the wrong way.
