### ISSUE TITLE
Using JEO category aggregation feature to address navigation issues

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#648]
Hi all,

I'd like to suggest an approach to tackling some of the navigation issues presented by the content asymmetry we currently face across the regional and country sites. It cannot address the issue of content asymmetry directly, only developing news summaries, topic pages, database items, announcements, maps and profiles will do that -- but this approach could help maximize exposure of content that does exist.

This approach utilizes existing functionality and could be implemented with relatively little development overhead , nor significant change to UI and content structure.

The JEO theme for WordPress features a customized presentation of WP categories to account for custom post types. Since categories are the feature we use to implement the taxonomic structure in WordPress, this feature effectively makes each category page a directory of content across types for any given category.

See an example at: https://opendevelopmentmekong.net/category/environment-and-natural-resources/

This feature was designed for exactly this purpose -- to encourage users to explore content with taxonomic category as the structure/directory. Currently, it is only accessible to users if they click on the hyperlink of a category, which is displayed in relatively small text at the top of all post types:

![image](https://cloud.githubusercontent.com/assets/1206387/21170281/4d20e714-c1f6-11e6-9fae-5760e4123a7f.png)

The category page is currently quite basic in terms of presentation and only covers four post types. My understanding is that this could be extended relatively easily to include maps, layers, datasets, library items and all content types, since all of the items housed on CKAN are now being rendered as WordPress entities as of UI 2.0. @acorbi please confirm if my understanding is correct.

My suggestion is that the design and function of this page is updated to account for all content types, and feature topic pages prominently as a visually-cued introduction to a topic.  This page could then be presented to users:

a) instead of topic pages under the 'topics' menu -- topic pages would be clearly emphasised in the case that they exist for that category, if not then the user sees all other available content under that topic. 

b) in the case of users navigating to a topic on a country site that does not have a topic page developed for that category -- users would see all other content of that category.

I look forward to hearing people's thoughts on how we could integrate this powerful functionality that is almost unused currently, and how it may be enhanced to best serve the platform.

**Comment by gimmemochi** [comment]
@DBishton please provide a screenshot/demo for how the "category" page look.

**Comment by DBishton** [comment]
@gimmemochi Please see the link above for 'environment and natural resources' category on ODM above. Screenshot of that below, with 'topic' tab  visible:

![image](https://cloud.githubusercontent.com/assets/1206387/21173775/0f337690-c20c-11e6-9ec3-4373339b900c.png)

**Comment by DBishton** [comment]
Note that I propose this screen be redesigned if we are to utilize it more heavily as suggested above.

**Comment by acorbi** [comment]
@DBishton @gimmemochi In general, I agree with Dan's proposed solution. 

I believe presenting the **Category page** is definitely better than the 404 screen. 

Enhancing it could be done without much effort:

> My understanding is that this could be extended relatively easily to include maps, layers, datasets, library items and all content types

Correct

>  topic pages would be clearly emphasised in the case that they exist for that category

Jup, I think, if available, topics (specially the specific topic, if available) should be presented at the top of the site more predominantly. Something like:

![0f337690-c20c-11e6-9ec3-4373339b900c](https://cloud.githubusercontent.com/assets/384894/21175768/4acdb81e-c1e4-11e6-9ece-447f43edc14a.png)

**Comment by jpeizer1** [comment]
This solution to use categories page more appropriately is a good one but should not be conflated with solving the more simple and straightforward PAGE NOT FOUND issue. This Category solution should be dealt with in an upcoming version.

1) This actually does not solve the primary problem PAGE NOT FOUND error when clicking between sites  -- as Dan suggests above. But that is the reason the navigation change was suggested in the first place so that clicking the country would take the user to the country home page and not a PAGE NOT FOUND page.

2) Has anyone factored in what it will take to negotiate with the partners to change their entire TOPIC presentation to Categories? What it will take to negotiate what the new Category page looks like with the Partners? How the Main Navigation menu's may change? Has anyone factored in the time it will take to make multiple languages look right on the categories page for each content type, because right now it doesn't look good: https://opendevelopmentcambodia.net/km/category/environment-and-natural-resources/

All negotiations take time and this is a major change -- which means months more of users clicking between countries  and getting PAGE NOT FOUND errors.

So I suggest we deal with the core problem at hand first and then give this solution,  that deals with other issues, the appropriate discussion bandwidth in a new version.

**Comment by Huyeng** [comment]
I think it is quite confuse to the users if the contents of the topic pages differently presented. How do you feel when you click the any topic  pages, sometimes, topic pages are shown, and sometimes other contents/posts are shown instead.  

> This page could then be presented to users:
a) instead of topic pages under the 'topics' menu -- topic pages would be clearly emphasised in the case that they exist for that category, if not then the user sees all other available content under that topic.
> b) in the case of users navigating to a topic on a country site that does not have a topic page developed for that category -- users would see all other content of that category.

I agreed with enhance the category page to make it looks better. 

PAGE NOT FOUND
From the user experiences that we learn from the  users, PAGE NOT FOUND always makes users thought that the website errors instead of related content/page is not existing.  Thus, I support JP, when the users click the country, it should take the user to the country home page if the related page/content doesn't exist.  This problem can be deal with quickly, right @acorbi?

**Comment by acorbi** [comment]
Hi @Huyeng thanks for your feedback. yes, implementing @jpeizer1's suggestion would be pretty quick ( ~30mins)

@thetaung2 @yanoak would you like to provide your thoughts on this navigation Issue?

**Comment by thetaung2** [comment]
Hi @acorbi , we experience the same here as @Huyeng. Users think it is the site error when they clicked on a topic and saw 404 Error. Agree to implement @jpeizer1's suggestion as an initial step.

**Comment by acorbi** [comment]
@jpeizer1 @DBishton @gimmemochi @Huyeng @thetaung2 @prustar I have changed the code so the user is taken to the homepage of the country site corresponding to the icon clicked. It has been currently deployed in PP. Please test and re-open this Issue in case you notice any problem.

**Comment by Huyeng** [comment]
@acorbi - I tested on PP,  the icons of the country was updated to the homepage of the country on click whether the page of the other country is existing or not. 
 
I would like to suggest that if the same page of other country site is available, it should be presented it, but if it is not available, it should redirect to the homepage instead.
For example, if the users on the land page of ODC, when they click on Mekong icon, it should go to Mekong's land page. However, when they click on Thailand icon, if the page is not available, it should go to the homepage instead. 
https://pp.opendevelopmentmekong.net/topics/land/   => https://pp.opendevelopmentcambodia.net/km/topics/land/  => https://thailand.pp.opendevelopmentmekong.net/

What do you think about this?

**Comment by acorbi** [comment]
@Huyeng I understand your suggestion. I think it could be an interesting alternative to the current implementation.

@jpeizer1 @prustar @thetaung2 @gimmemochi @DBishton what huyeng proposes is:

When the user clicks on the country icon
- and the content is available -> take the user to the content
- if not available -> show a 404 screen informing the user that it is going to be taken to the homepage because the content is not available. After 3 or 5 seconds the user is redirected automatically.

What are everyone's thoughts?
