### ISSUE TITLE
Some texts on detail page are not translated

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#655]
https://opendevelopmentcambodia.net/km/dataset/?id=http-web-archive-org-web-20150708083757-http-www-cdri-org-kh-webdata-download-wp-wp63e-pdf

![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/21180312/f50fcf4c-c22a-11e6-826d-078b665071a8.jpg)

**Comment by acorbi** [comment]
@Huyeng On https://data.opendevelopmentmekong.net/api/3/action/package_show?id=http-web-archive-org-web-20150708083757-http-www-cdri-org-kh-webdata-download-wp-wp63e-pdf you can see that:

- Publication date is not a multilingual field ("marc21_260c)
- Publisher only has been entered in english (marc21_260b)

- In order to be able to localize **Document type** we need first to fix https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/636 , which I am intending to fix until end of the week

**Comment by Huyeng** [comment]
Issue moved to other repository. 
https://github.com/OpenDevelopmentMekong/wpckan/issues/204
