### ISSUE TITLE
Add filter by record type option on new data page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#777]
On the new data page layout, a **Filter by record type** should be added as a dropdown box which would allow the user to filter the results by the record types currently being maintained:

- Datasets
- Library publications
- Laws 
- Agreements

![screenshot from 2017-03-13 10-58-19](https://cloud.githubusercontent.com/assets/384894/23849506/215e2930-07dc-11e7-8ade-8ab32ad83eed.png)

**Comment by DragonVirus** [comment]
i removed it cuz as i understand currently the pages will be implemented as separate pages eg. Data Page, Library records Page, Law Page such as.

**Comment by acorbi** [comment]
@DragonVirus That is a valid argument. Let's keep it as it is now (allowing the creation of separate pages for other record types) and just implement this Issue if we need to.

**Comment by acorbi** [comment]
@prustar what is your opinion around this? Do we need data pages which expose different types of records (datasets, laws, library publications, agreements) on the same page or are we only going to have data pages associated to individual record types?

**Comment by prustar** [comment]
@acorbi @DragonVirus -- I initial thought was to have separate pages for data types and that the universal search would be where we could filter and then be taken to the individual pages. This is because we have specific law page for instance that collates only the laws which needs different metadata displayed and also different filter options. 
There needs to be a function for the user to navigate between these dataset types and back to the central search. I don't see on the design how this will be implemented yet.

**Comment by acorbi** [comment]
Fixed now
