### ISSUE TITLE
Filter by country not filtering properly

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#778]
On https://pp.opendevelopmentmekong.net/data?taxonomy=all&country=thailand&language=all&license=all&query=, if the **Filter by country** is changed to **thailand** and the search button is clicked, the list of results contain records from mekong and cambodia. The expected behaviour would be that only contents from thailand, if any, would be listed.

![screenshot from 2017-03-13 11-33-33](https://cloud.githubusercontent.com/assets/384894/23850783/2a72e254-07e1-11e7-888b-9afd2b49ef36.png)

**Comment by DragonVirus** [comment]
As i mentioned in previous meeting, it's cuz i use `extras_odm_spatial_range` to filter but the field is showing with `organization` field. This should be changed to country flag instead of showing the organization logo. But the question is "Are we gonna show both organization logo and country flag ?"

**Comment by acorbi** [comment]
@DragonVirus thanks for clarification. Let's use **extras_odm_spatial_range** for filtering, as it is now but showing the flags instead of the organization.  We do not need to add filter by organization at this point.

**Comment by acorbi** [comment]
Closing in favour of https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/770
