### ISSUE TITLE
Take users to category page and not to topic page on taxonomy widget

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#813]
As a demostrator for the improvents on the taxonomic navigation discussed recently, the **Topic areas** widget should be adapted so the user is taken to the corresponding category pages (example: https://pp.opendevelopmentcambodia.net/category/social-land-concessions/ instead of https://pp.opendevelopmentcambodia.net/topics/social-land-concessions/)

![screenshot from 2017-03-28 12-45-43](https://cloud.githubusercontent.com/assets/384894/24401427/a5e43efe-13b4-11e7-8a17-37aba1d241af.png)

**Comment by acorbi** [comment]
Hi @Huyeng. this branch is experimental only. This means that it is intented to pilot a possible change that will be discuss with ODC in case ODM wants to implement it. 

See the corresponding PR https://github.com/OpenDevelopmentMekong/wp-odm_theme/pull/814 has a message indicating it.

**Comment by Huyeng** [comment]
Thanks for your understanding.

**Comment by prustar** [comment]
Using the example you provide for topic social land concession which is in the taxonomy you get taken to the content page if it's left as is correct: i.e. this page: \
![image](https://cloud.githubusercontent.com/assets/14996905/24657027/02f96d98-196f-11e7-82e9-131f17d3ad1b.png)

If you use categories for this same topic you get to this page: 
![image](https://cloud.githubusercontent.com/assets/14996905/24657050/1cb01cbe-196f-11e7-80f9-5f6cb6ecc19e.png)

Which again only displays first off all the news which was the issue with the display of the search previously and something that we changed due to user feedback. 
I understand we could rearrange these tabs however the only other tab with content is the TOPIC page with the content as expected for social land concessions. 

Considering that ODC has the most content I agree that this would not benefit their site and actually detract users to an extent. 

For ODM as the majority of the content is news then when a user selects a category (which is still the taxonomy term?) then they are likely still to be taken to a blank page. I'm still awaiting a use case or scenario where implementing this would actually add value to our platform rather than simply continue to emphasise the fact that we have very little content on ODM still.

**Comment by acorbi** [comment]
@Huyeng @DBishton @prustar

FYI: After discussing with @DBishton I have done this change **configurable**, this means that now editors can decide the behaviour of the widget via a configuration option:

![screenshot from 2017-04-04 15-19-55](https://cloud.githubusercontent.com/assets/384894/24658561/583de420-194a-11e7-8060-c2da941dd52b.png)
_See links should take user to:_

The reasoning behind doing this configurable is mainly to make demostrating this possible without interfering with the further development and deployment of other issues.

@prustar  now to your comment:

> I understand we could rearrange these tabs however the only other tab with content is the TOPIC page with the content as expected for social land concessions.

In case we would go down this road and change the logic of the widget, we should definitelly improve the layout of the **category pages** so topics are presented more predominantly as news and the whole page provides more value. I believe a brainstorming session around this would be very positive.
