### ISSUE TITLE
"Search result for" box on the left

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#830]
This is the first page that displays when you search: but it's different when you select all below: 
![image](https://cloud.githubusercontent.com/assets/14996905/24649963/f09b3828-1952-11e7-9e83-d305fad2d408.png)
After you select all: the list of resources types etc are now placed on the left. I would change this to what we discussed. The summary would be automatically on the left when the page appears and the first one to be displayed will be datasets. 
![image](https://cloud.githubusercontent.com/assets/14996905/24649998/0760a52a-1953-11e7-962a-be86731444a8.png)

**Comment by acorbi** [comment]
Thanks @prustar  for your feedback:

If I understand your point properly, you would add the **Search results for "X"** box also on the first screen. By doing this we would give users the chance to explore results from a particular content type faster since they would not need to scroll down and click "See all" , right?

That should be easy, I could do it in the next hours...

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/39 where it belongs
