### ISSUE TITLE
Fuzzy Logic for predictive search

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#867]
@acorbi  We tested this somewhat today in our meeting and it wasn't working as expected. We purposely miss spelt things and there were no alternative options presented or suggested to the user?

**Comment by acorbi** [comment]
@prustar which terms were you experiment with? can you provide more concrete details on the expected behaviour and what you observed?

**Comment by prustar** [comment]
@acorbi can't remember the exact terms we used that day but just did a quick search for ratanakiri and rattanakiri - difference of one letter and you get different results: 

8 for only one t and 2 for double t - the fuzzy logic should actually bring up all these results so 10 in total potentially more. I gather however as these results are exact matches that's why it's doing this. In other applications this is set by the user to allow for discrepancies but it would be great to provide it without having to ask the user to set it.

**Comment by acorbi** [comment]
For reference: http://stackoverflow.com/questions/9883151/solr-fuzzy-search-for-similar-words

**Comment by acorbi** [comment]
@prustar I found out there is currently an issue with multi-term synonyms on the search engine we use. At this point, we can only maintain a list of single-term synonyms such as ratanakiri -> rattanakiri or rattannakiri, etc...

I have opened https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/48 in order to approach the multi-term issue
