### ISSUE TITLE
Display 'last updated' date instead of 'date created' on topic pages

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/wp-odm_theme#873]
Hi @acorbi ,

Topic pages currently  display the date the page was first published under the title:
![image](https://cloud.githubusercontent.com/assets/1206387/25577993/b195a968-2e94-11e7-99bd-5dc9bf0db51f.png)

For ODM, we would like to display the date the page was last updated here. Is this currently configurable? If not, could you suggest a way in which it could be implemented? Would it be relatively straightforward to make this configurable, in case country partners would like to maintain current functionality?

**Comment by Huyeng** [comment]
ODC team used to discuss about this whether the date under the Topics Title should be the created date or last updated date.  In Wordpress, if using the modified date as the last updated date, it is not correct because sometimes, the content is not updated, but unused some blank spaces or codes are removed or other settings are changed. 

Since all the topic pages that ODC published has added the Last updated date at the end of the content, so ODC kept the created date under the title as consistent as other contents.

**Comment by prustar** [comment]
@huyeng you have a point.

**Comment by acorbi** [comment]
@DBishton please coordinate with ODC to agree on a consistent way of providing creawtion and modification date on topic pages

**Comment by DBishton** [comment]
Thanks for the comments all.

@acorbi @Huyeng -- a suggested solution for the issue Huy Eng raised about updated date reflecting non-content relate changes (removing spaces, changing formatting) etc. 

A checkbox allowing editors to reflect an update -- it is checked when content is updated, but not when other changes are made. @acorbi would this be a relatively straightforward implementation?

If ODC and other partners want to continue to update the dates manually and have the date created shown at the top of the page and in topic widgets, my view is that this is an area of functionality in which partners can choose their ideal behaviour. Which date is displayed has little impact on users or UI consistency (as search page layout or overall UI design would, for example).

**Comment by acorbi** [comment]
@DBishton @Huyeng My comments:

> In Wordpress, if using the modified date as the last updated date, it is not correct because sometimes, the content is not updated, but unused some blank spaces or codes are removed or other settings are changed.

Although I understand what you say here @Huyeng, I think removing whitespaces or changing settings DOES mean that the post has been updated and it is even positive to reflect a more frequent set of changes on the front-end. In my opinion, this should not be the reason for not showing the updated date instead of the created date on the top of the posts.

> Since all the topic pages that ODC published has added the Last updated date at the end of the content, so ODC kept the created date under the title as consistent as other contents.

Adding the last updated date manually involves more work and I see this as a counterproductive and error-prone approach to something as common in blogging/publishing sites as showing such a date.

> A checkbox allowing editors to reflect an update -- it is checked when content is updated, but not when other changes are made. @acorbi would this be a relatively straightforward implementation?

@DBishton Although it makes sense, I would disadvice to increase the complexity of the editorial workflow for something, as I already said, so common.

> If ODC and other partners want to continue to update the dates manually and have the date created shown at the top of the page and in topic widgets, my view is that this is an area of functionality in which partners can choose their ideal behaviour. Which date is displayed has little impact on users or UI consistency (as search page layout or overall UI design would, for example).

I want to propose following combined approach, which basically consists on showing both dates as shown in the screenshot below. please @Huyeng and @DBishton provide your input:

![date](https://cloud.githubusercontent.com/assets/384894/25793969/338ed860-33cf-11e7-96b5-1f26e83047a0.png)

**In case there is no agreement on this**,  what I would do is to add yet-another configuration option under **Appearance > Open Development** so teams can choose whether to show creation or updated date under the title.

Waiting for your feedback now

**Comment by DBishton** [comment]
Hi @acorbi,

Thank you for the careful consideration and this proposal. This works for me, my only question would be about display: text wrapping of categories in the case of longer category titles and more of them to list. Perhaps they could sit under the created and updated dates?

I agree with your points re: overcomplicating the editorial workflow and value of minor updates. It's fine for me if the updated date reflects even minor changes, these often still represent an improvement to the page. 

@Huyeng Please provide feedback from ODC on this ASAP, this upgrade is a high priority request from home office.

**Comment by acorbi** [comment]
@DBishton the list of categories would wrap to the next line as it does now... it should not be an issue

**Comment by Huyeng** [comment]
What will you get the last updated from, the modify date?

**Comment by Huyeng** [comment]
> In case there is no agreement on this, what I would do is to add yet-another configuration option under Appearance > Open Development so teams can choose whether to show creation or updated date under the title.

It is ok if you would like to show like that. However, personally, it doesn't make scenes when using the modify date as the updated date of the content. 

According to your template, there are two dates display under the title, is it what you expected to show?

**Comment by Huyeng** [comment]
> In case there is no agreement on this, what I would do is to add yet-another configuration option under Appearance > Open Development so teams can choose whether to show creation or updated date under the title.

It is ok if you would like to show like that. However, personally, it doesn't make scenes when using the modify date as the updated date of the content. 

According to your template, there are two dates display under the title, will it show both after implement or either one?

If you enable this configure, please set the created as default. 
ODC won't enable the modified date because it will have different dates between the "date under the title" and "last updated date of content" that can make the users be confuse. For example, the modified date can be grater than "last updated date", so it doesn't make sense. Otherwise, we need to edit hundred pages to remove the words "Last updated date" of each content.

**Comment by acorbi** [comment]
> ODC won't enable the modified date because it will have different dates between the "date under the title" and "last updated date of content" that can make the users be confuse

@Huyeng I am proposing showing **both**, exactly as my mockup represents. Creation date and modification date, both in the same line below the title.

From your reply I get the sense that ODC would not agree with this change, is it like that? In this case I would implement the "configurable alternative". Please confirm

**Comment by Huyeng** [comment]
As the case I mentioned above, it will make users be confuse with displaying the Created date, modified date and last updated date on a page together. No one understand clearly about the using icons sometimes. 
Please create an option in the configuration of Open Development if they would like to display it on the topic page.
