### ISSUE TITLE
Category page: Landing / topic pages non-clickable, Layers should be renamed

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/wp-odm_theme#888]
@acorbi @DBishton  There are a few things:
* Suggestion: Add 'landing/topic page' title on top of the thumbnail, hyperlink it to the page
* Question: Does it only show the landing page? And other pages are show in **Related briefings**?
* Suggestion: Layers is an abstract term. Call it **Map layers** or **Maps**?
https://pp.opendevelopmentmekong.net/category/land?queried_post_type=laws_record

<img width="1174" alt="screen shot 2017-05-03 at 6 16 26 pm" src="https://cloud.githubusercontent.com/assets/6489398/25658499/6625dd5a-302d-11e7-9d0d-18d649edd05d.png">

**Comment by acorbi** [comment]
hey @gimmemochi thanks for your suggestions, my comments below:

> Suggestion: Add 'landing/topic page' title on top of the thumbnail, hyperlink it to the page

There was a title before but I removed it because it is duplicated with the page's title

> Question: Does it only show the landing page? And other pages are show in Related briefings?

It shows the corresponding landing page (briefing) if available. The **related briefings** would provide links to other **briefings** but now that you mention it, each category page should focus only on a single briefing and provide navigation possibilities to other **topics** via the widget. 

> Suggestion: Layers is an abstract term. Call it Map layers or Maps?

Agreed, will do

**Comment by acorbi** [comment]
@gimmemochi see discussion on https://github.com/OpenDevelopmentMekong/jeo/issues/55
