### ISSUE TITLE
Can we tag 'author' within the list of results 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_theme#968]
i.e. here see red line: 

![image](https://cloud.githubusercontent.com/assets/14996905/26575798/d9dc9b7a-4550-11e7-989e-9bdf4dd83b73.png)

We have four fields for author can we figure out a consistent logic to present the author on the library records. 

i.e. if there is no single author present the multiple authors and if there are no authors then present the single corporate author then the multiple corporate author.

**Comment by acorbi** [comment]
@prustar technically possible to implement.

question: Would you show authors on other record types as well?

@gimmemochi @DBishton @Huyeng @ChandaraKhun @DragonVirus @thetaung2 any feedback?

**Comment by Huyeng** [comment]
ODC team already proposed the idea to show the library record in the search template design. 
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/26613557/959b1406-45e5-11e7-89cf-9776f7a6915d.jpg)

**Comment by DBishton** [comment]
@Huyeng I like this design, and glad to see ODC supports the idea.

> question: Would you show authors on other record types as 
@acorbi  I don't think this feature would be desireable or needed on other data types.

@acorbi @prustar We should discuss logic -- not all library items have individual authors -- those that do not should have a corporate author instead. Those that do not have a corporate or individual author entered should display publisher instead. None of these fields are mandatory, but in almost all cases at least one will be filled out.

So, I assume the logic should be:

1. Display 'Author (individual)' if not null, but if it is;

2. Display 'Author(corporate)' is not null, but if it is;

3. Display 'Publisher'

@prustar @acorbi What do you think? Any other considerations? Should we display co-authors (individual or corporate) as well? In ideal world I'd say yes, but this could definitely present design/presentation problems in cases such as journal articles with a long list of contributors.

**Comment by acorbi** [comment]
thanks for your comments @DBishton , your proposed logic is very clear and helped me to envision a possible implementation. 

I would be OK with the logic you propose. In case the record does not have any Authors or Publishers, then we do not show anything, I would say.

Waiting for @prustar's comments...

**Comment by ChandaraKhun** [comment]
@DBishton @prustar @Huyeng @acorbi To my understanding, two main fields to underline under each library record shall be author/editor & publisher. In most of the cases, there shall be names of author/editor & publisher clearly mentioned in the cover and/or, in some cases, immediately in the first few pages of the work. To me, it is not necessary to distinguish individual/co- vs. corporate author. 

I understand what @Dan did mention, whereby we might have the same names for both authors & publisher; but it is an exceptional/rare case. Example, for ADB/WB publications, we still can find a group of responsible persons for the publications and its related projects, sometimes in its acknowledgement instead of the first few pages at the beginning of each publication.

**Comment by acorbi** [comment]
moved to https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/123
