### ISSUE TITLE
No image background for these topics

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_theme#97]
No images backgrounds for Disastres... and Urban Admin.... Unlike the boxes below them

![noimages](https://cloud.githubusercontent.com/assets/16559612/16899185/3ecf5b90-4bc8-11e6-8ef4-51436201ff0d.JPG)

**Comment by acorbi** [comment]
@jpeizer1 this is an editorial issue. **featured images** should now be added to all those posts in order for the background images to appear. @DBishton  I believe this can be a time consuming thing and since we are currently testing in PP, it is not going to be final (on production). This should be done in production.

My suggestion is that we all imagine that all the boxes will have background images and focus on other more critical issues.

**Comment by acorbi** [comment]
Closing. @DBishton can you check that all relevant contents in production sites do have **featured image**? thanks
