### ISSUE TITLE
news menu-item (newspaper) not showing up on homepage

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#991]
On all homepages where the news menu-item is exposed https://pp.opendevelopmentmyanmar.net, https://pp.opendevelopmentmekong.net, https://pp.opendevelopmentcambodia.net , this is being hidden when the page loads. This does not happen on such as the search page or the profiles page https://pp.opendevelopmentmyanmar.net/my/profiles https://pp.opendevelopmentmekong.net/?s=land

![screenshot from 2017-06-06 12-07-31](https://cloud.githubusercontent.com/assets/384894/26824345/43e84018-4ab1-11e7-99c4-47f984d9b6cc.png)
![screenshot from 2017-06-06 12-08-00](https://cloud.githubusercontent.com/assets/384894/26824346/43eae228-4ab1-11e7-8bd0-eec25f562c56.png)
![screenshot from 2017-06-06 12-11-36](https://cloud.githubusercontent.com/assets/384894/26824359/4eb6b272-4ab1-11e7-9d72-f2e770190fa7.png)

**Comment by acorbi** [comment]
@Huyeng @DragonVirus this issue is **SUPER** weird and is driving me nuts.  Can you reproduce it? If so, do you have an idea why the newspaper icon is dissapearing on the homepage? Makes no sense to me, does not happen with other icons....

**Comment by Huyeng** [comment]
From my observation on page loading, that news icon was hidden when the Slideshow is appearing.
I could assume there are some conflicted between the fonts using in the theme and the Slideshow plugin because only the homepage that the icon doesn't show and only homepage that has the slideshow as well. 
If view the source code, the homepage, there are three font-awesome fonts are included from different directories, Mega, Bower-components and the link below, while on other pages have included only two (Mega and Bower). 

Once you try to remove the link tag below on homepage using the Browser Inspected Element, then the news icon will appear. 
<link rel="stylesheet" id="font-awesome-css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css?ver=3.1.5.4" type="text/css" media="all">

Hope this is a helpful clue to fix the issue.

**Comment by acorbi** [comment]
thanks @Huyeng . it was indeed to the fact that featured-articles pro was integrating version 4.1 of font-awesome as dependency which was causing the conflict. I have updated the code on the plugin and asked the developers to update the dependency's version... thanks for your help!
